BaseLPPA/Presentation/Lppa.UI.Web/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;

namespace Lppa.UI.Web.Controllers
{
    public class SolicitudController : Controller
    {
        private LppaBD db = new LppaBD();

        // GET: Solicitud
        public ActionResult Index()
        {
            return View(db.Solicitud.ToList());
        }


        public ActionResult SolicitudCliente(string cliente, string dni)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;
            return View();
        }

        public ActionResult ImprimirTarjeta(string cliente)
        {
            ViewBag.Cliente = cliente;
            return View();
        }


        [HttpPost]
        public ActionResult SolicitudCliente(ViewModels.ContratoViewModel solicitud, string cliente, string dni)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;

            var customerFound = new ClienteRepository();
            var customer = customerFound.SearhByDNI(long.Parse(dni));

            var tarjetaFound = new TarjetaRepository();
            var tarjeta = tarjetaFound.searchByDNI(customer.ID);

            try
            {
                var s = new Solicitud()
                {
                    Celular = solicitud.Celular,
                    Email = solicitud.Email,
                    //FirmaCliente = solicitud.FirmaElectronica,
                    //FotoCliente = solicitud.Imagen,
                    ChangedBy = Guid.NewGuid().ToString().Substring(0, 8),
                    ChangedOn = DateTime.Now,
                    CreatedBy = Guid.NewGuid().ToString().Substring(0, 8),
                    CreatedOn = DateTime.Now,
                    CodEstado = 1,
                    IDCliente = customer.ID,
                    IDTarjeta = tarjeta.ID

                };
                db.Solicitud.Add(s);
                db.SaveChanges();

                ViewBag.Cliente = cliente;
                ViewBag.ClienteDNI = dni;
                return View();
            }
            catch
            {
                throw null;
            }


         
        }


        // GET: Solicitud/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // GET: Solicitud/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Solicitud/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IDCliente,IDTarjeta,CodEstado,FotoCliente,FirmaCliente,Email,Celular,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Solicitud.Add(solicitud);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(solicitud);
        }

        // GET: Solicitud/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // POST: Solicitud/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IDCliente,IDTarjeta,CodEstado,FotoCliente,FirmaCliente,Email,Celular,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Solicitud solicitud)
        {
            if (ModelState.IsValid)
            {
                db.Entry(solicitud).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(solicitud);
        }

        // GET: Solicitud/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Solicitud solicitud = db.Solicitud.Find(id);
            if (solicitud == null)
            {
                return HttpNotFound();
            }
            return View(solicitud);
        }

        // POST: Solicitud/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Solicitud solicitud = db.Solicitud.Find(id);
            db.Solicitud.Remove(solicitud);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/TarjetaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;
using Lppa.Entities;
using Lppa.UI.Process;

namespace Lppa.UI.Web.Controllers
{
    public class TarjetaController : Controller
    {
        private LppaBD db = new LppaBD();

        // GET: Tarjeta
        public ActionResult Index()
        {
            return View(db.Tarjeta.ToList());
        }

        // GET: Tarjeta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Create
        public ActionResult Create()
        {
            return View();
        }
        
        public ActionResult TarjetaCliente(string cliente, string dni)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;
            return View();
        }

        [HttpPost]
        public ActionResult TarjetaCliente(TarjetaEntity tarjeta, string dni)
        {
            var tcc = new TarjetaComponentController();
            tcc.insert(tarjeta, long.Parse(dni));

            var customerFound = new ClienteRepository();
            var customer = customerFound.SearhByDNI(long.Parse(dni));
            string nombre = customer.Nombre + " " + customer.Apellido;
            ViewBag.Cliente = nombre;
            ViewBag.ClienteDNI = dni;
            return View();
        }

        //[HttpGet]
        //public ActionResult _TarjetaCliente(long dni)
        //{
        //    var ccc = new ClienteComponentController();
        //    ccc.BuscarPorDNI(dni);


        //    return View();
        //}



        // POST: Tarjeta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IDBanco,IDCliente,Marca,FechaEmision,FechaVencimiento,CodVerificacion,Limite,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Tarjeta tarjeta)
        {
            if (ModelState.IsValid)
            {
                db.Tarjeta.Add(tarjeta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tarjeta);
        }

        // GET: Tarjeta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // POST: Tarjeta/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IDBanco,IDCliente,Marca,FechaEmision,FechaVencimiento,CodVerificacion,Limite,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Tarjeta tarjeta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarjeta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // POST: Tarjeta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            db.Tarjeta.Remove(tarjeta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Views/Tarjeta/Create.cshtml
@model Lppa.Data.Tarjeta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Tarjeta</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.IDBanco, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDBanco, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDBanco, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IDCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDCliente, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Marca, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Marca, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Marca, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.FechaEmision, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaEmision, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaEmision, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.FechaVencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaVencimiento, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaVencimiento, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CodVerificacion, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CodVerificacion, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodVerificacion, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Limite, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Limite, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Limite, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CodEstado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CodEstado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodEstado, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedBy, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Tarjeta/Delete.cshtml
@model Lppa.Data.Tarjeta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Tarjeta</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IDBanco)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDBanco)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDCliente)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDCliente)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Marca)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Marca)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaEmision)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaEmision)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaVencimiento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaVencimiento)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodVerificacion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodVerificacion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Limite)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Limite)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodEstado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodEstado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedOn)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Tarjeta/Details.cshtml
@model Lppa.Data.Tarjeta

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Tarjeta</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.IDBanco)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDBanco)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDCliente)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDCliente)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Marca)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Marca)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaEmision)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaEmision)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaVencimiento)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaVencimiento)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodVerificacion)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodVerificacion)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Limite)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Limite)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodEstado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodEstado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedOn)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Tarjeta/Index.cshtml
@model IEnumerable<Lppa.Data.Tarjeta>
    @using Lppa.UI.Web.Models;

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>

    @section ProgressBar{
        @Html.Partial("_ProgressBar");
        
        }
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IDBanco)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Marca)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaEmision)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaVencimiento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodVerificacion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Limite)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodEstado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IDBanco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Marca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaEmision)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaVencimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodVerificacion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Limite)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodEstado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangedOn)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Tarjeta/TarjetaCliente.cshtml
@model Lppa.Data.Tarjeta

@{
    ViewBag.Title = "Tarjetas";
    
}


<html>
<head>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <link href="~/Content/ProgressBar.css" rel="stylesheet" />
</head>
<body>
    @Html.Partial("_ProgressBar2")

    <h2 >Tipo de Tarjeta</h2>
    @using (Html.BeginForm("TarjetaCliente", "Tarjeta", FormMethod.Post, new { tarjeta = Model, dni = ViewBag.ClienteDNI }))
    {
        @Html.AntiForgeryToken()

        <div class="col-md-6">
            <div class="panel panel-success">
                <div class="panel-heading panel-title" style="background-color:#00adff; color:antiquewhite;">@ViewBag.Cliente - DNI: @ViewBag.ClienteDNI</div>
                <div class="panel-body">

                    <div class="form-group col-md-7">
                        @{
                            var tipoTarjeta = new List<SelectListItem>()
                            {
                                new SelectListItem() {Text = "Visa", Value = "Visa"},
                                new SelectListItem() {Text = "American Express", Value = "American Express"},
                                new SelectListItem() {Text = "MasterCard", Value = "MasterCard"}
                            };
                        }
                        @Html.LabelFor(m => m.Marca)
                        <div class="input-group">
                            <span class="input-group-addon">
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </span>
                            @Html.DropDownListFor(m => m.Marca, tipoTarjeta, new { @class = "form-control" })
                        </div>
                    </div>


                </div>
            </div>
        </div>
        

        <input type="hidden" value=@ViewBag.ClienteDNI name="dni" />
            
        <input type="submit" value="Guardar" class="btn btn-primary" />


                            }


    <div class="form-group">
        <div class="col-md-offset-10 col-md-10">
            @Html.ActionLink("Continuar", "SolicitudCliente", "Solicitud", new {cliente = ViewBag.Cliente, dni = ViewBag.ClienteDNI }, null)
        </div>
    </div>


</body>
</html>