BaseLPPA/Presentation/Lppa.UI.Web/ViewModels/ContratoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using Lppa.Entities;

namespace Lppa.UI.Web.ViewModels
{
    public class ContratoViewModel 
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        public string Celular { get; set; }

        [DataType(DataType.Upload)]
        public HttpPostedFileBase Imagen { get; set; }

        [DataType(DataType.Upload)]
        public HttpPostedFileBase FirmaElectronica { get; set; }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;
using Lppa.UI.Process;
using Lppa.Entities;

namespace Lppa.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        private LppaBD db = new LppaBD();
        public string resultado { get; set; }

        public ActionResult Index()
        {
            ViewBag.Veraz = resultado;
            return View(db.Cliente.ToList());
        }

        public ActionResult PasosCliente()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Contrato()
        {
            ViewBag.Progress = 3;
            return PartialView();
        }

        public ActionResult ValidarVeraz(long dni)
        {
            var vp = new VerazComponentController();
            resultado = vp.ValidarVeraz(dni);

            ViewBag.Veraz = resultado;
            ViewBag.DNI = dni;
            return RedirectToAction("Index", new { result = resultado });
        }

        [HttpPost]
        public ActionResult ValidarVeraz(string dni)
        {
            if (dni.ToString() == "Enviar consulta")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var vp = new VerazComponentController();
                resultado = vp.ValidarVeraz(long.Parse(dni));

                ViewBag.Veraz = resultado;

                var customerFound = new ClienteRepository();
                var customer = customerFound.getID(long.Parse(dni));
                string NombreCliente = customer.Nombre + " " + customer.Apellido; 
             
                return RedirectToAction("DatosCliente", new { result = resultado, dni = dni, cliente = NombreCliente});
                //return RedirectToAction("DatosCliente");
            }


        }

        [HttpPost]
        public ActionResult Index(long dni)
        {


            var ccc = new ClienteComponentController();
            var nuevoCliente = ccc.BuscarPorDNI(dni);

            if (nuevoCliente == null)
            {

                return View(new List<Lppa.Data.Cliente>());

            }
            else
            {
                var c = new Cliente()
                {
                    Nombre = nuevoCliente.Nombre,
                    Apellido = nuevoCliente.Apellido,
                    DNI = nuevoCliente.DNI,
                    Domicilio = nuevoCliente.Domicilio,
                    Sexo = nuevoCliente.Sexo,
                    Ocupacion = nuevoCliente.Ocupacion,
                    FechaNacimiento = nuevoCliente.FechaNacimiento,
                    EstadoCivil = nuevoCliente.EstadoCivil,
                    Ingreso = nuevoCliente.Ingreso,
                    ChangedBy = nuevoCliente.ChangedBy,
                    ChangedOn = nuevoCliente.ChangedOn,
                    CodEstado = nuevoCliente.CodEstado,
                    CreatedBy = nuevoCliente.CreatedBy,
                    CreatedOn = nuevoCliente.CreatedOn
                };


                var lista = new List<Cliente>();
                lista.Add(c);

                return View(lista);
            }


        }

        // GET: Cliente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Progress = 1;
            return View();


        }

        public ActionResult DatosCliente(string result, string dni, string cliente)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;
            ViewBag.Veraz = result;
            return View();
        }

  


        [HttpPost]
        public ActionResult DatosCliente(ClienteEntity cliente)
        {
            var ccc = new ClienteComponentController();
            ccc.AgregarunCliente(cliente);
            
            ViewBag.Cliente = cliente.Nombre + " " + cliente.Apellido;
            ViewBag.ClienteDNI = cliente.DNI;
          
            //return RedirectToAction("Index", new { result = "", dni = cliente.DNI });
            ViewBag.Respuesta = "Cliente " + ViewBag.Cliente + " fue creado con Exito!!";
            return View();


        }

        // POST: Cliente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Nombre,Apellido,DNI,Domicilio,EstadoCivil,FechaNacimiento,Ingreso,Sexo,Ocupacion,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Cliente cliente)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Cliente.Add(cliente);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(cliente);
        //}

        // GET: Cliente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Apellido,DNI,Domicilio,EstadoCivil,FechaNacimiento,Ingreso,Sexo,Ocupacion,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/ContratoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;

namespace Lppa.UI.Web.Controllers
{
    public class ContratoController : Controller
    {
        private LppaBD db = new LppaBD();

        // GET: Contrato
        public ActionResult Index()
        {
            return View(db.Contrato.ToList());
        }

        public ActionResult ContratoCliente()
        {
            return View();
        }

        public ActionResult ImprimirTarjeta()
        {
            return View();
        }


        // GET: Contrato/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(id);
            if (contrato == null)
            {
                return HttpNotFound();
            }
            return View(contrato);
        }

        // GET: Contrato/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Contrato/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FechaAlta,FechaBaja,IDCliente,IDTarjeta,IDUsuario,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Contrato contrato)
        {
            if (ModelState.IsValid)
            {
                db.Contrato.Add(contrato);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(contrato);
        }

        // GET: Contrato/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(id);
            if (contrato == null)
            {
                return HttpNotFound();
            }
            return View(contrato);
        }

        // POST: Contrato/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FechaAlta,FechaBaja,IDCliente,IDTarjeta,IDUsuario,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Contrato contrato)
        {
            if (ModelState.IsValid)
            {
                db.Entry(contrato).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(contrato);
        }

        // GET: Contrato/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Contrato contrato = db.Contrato.Find(id);
            if (contrato == null)
            {
                return HttpNotFound();
            }
            return View(contrato);
        }

        // POST: Contrato/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Contrato contrato = db.Contrato.Find(id);
            db.Contrato.Remove(contrato);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/ContratoCliente.cshtml
@model Lppa.UI.Web.ViewModels.ContratoViewModel
@{
    ViewBag.Title = "Contacto";
}
<html>
<head>


</head>
<body>

    @Html.Partial("_ProgressBar3")

    <div class="col-md-12">
        <h2 class="page-header">Contacto</h2>
    </div>

    <div>
        @using (Html.BeginForm("Contacto", "Cliente", FormMethod.Post, new { @class = "form", enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <div class="col-md-10">
                @Html.ValidationSummary()
            </div>
            <div class="col-md-10">
                <div class="panel panel-success">
                    <div class="panel-heading panel-title" style="color: white; background-color: rgb(0, 173, 255);">Datos de Contacto</div>
                    <div class="panel-body">
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Email)
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-envelope"></span>
                                </span>
                                @Html.TextBoxFor(m => m.Email, new { @class = "form-control required" })
                            </div>
                        </div>
                        @*<div class="form-group col-md-6">
                                @Html.LabelFor(m => m.Telefono)
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-phone-alt"></span>
                                    </span>
                                    @Html.TextBoxFor(m => m.Telefono, new { @class = "form-control required" })
                                </div>
                            </div>*@
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Celular)
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-phone"></span>
                                </span>
                                @Html.TextBoxFor(m => m.Celular, new { @class = "form-control required" })
                            </div>
                        </div>
                        <div class="form-group col-md-12">
                            @Html.Label("Seleccione su Foto")
                            @Html.TextBoxFor(m => m.Imagen, new { type = "file" })
                        </div>
                        <div class="form-group col-md-12">
                            @Html.Label("Seleccione su Firma Electrónica")
                            @Html.TextBoxFor(m => m.FirmaElectronica, new { type = "file" })
                        </div>
                    </div>
                </div>
            </div>


            @*<div class="col-md-12">
                    <input type="submit" class="btn btn-primary pull-right" value="Aceptar" />
                </div>*@

            <div class="form-group">
                <div class="col-md-offset-10 col-md-10">
                    @Html.ActionLink("Continuar", "ImprimirTarjeta", "Contrato")
                </div>
            </div>

        }
    </div>

</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/Create.cshtml
@model Lppa.Data.Contrato

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Contrato</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FechaAlta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaAlta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaAlta, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.FechaBaja, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FechaBaja, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FechaBaja, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IDCliente, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDCliente, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDCliente, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IDTarjeta, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDTarjeta, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDTarjeta, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.IDUsuario, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.IDUsuario, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.IDUsuario, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CodEstado, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CodEstado, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CodEstado, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedBy, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.CreatedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreatedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreatedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangedBy, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedBy, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedBy, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.ChangedOn, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ChangedOn, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ChangedOn, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/Delete.cshtml
@model Lppa.Data.Contrato

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Contrato</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaAlta)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaBaja)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaBaja)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDCliente)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDCliente)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDTarjeta)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDTarjeta)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDUsuario)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDUsuario)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodEstado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodEstado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedOn)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/Details.cshtml
@model Lppa.Data.Contrato

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Contrato</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaAlta)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.FechaBaja)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.FechaBaja)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDCliente)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDCliente)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDTarjeta)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDTarjeta)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.IDUsuario)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.IDUsuario)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CodEstado)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CodEstado)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.CreatedOn)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedBy)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.ChangedOn)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/ImprimirTarjeta.cshtml
<html>
<head>
    <title>Barra de progreso en Botstrap</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <link href="~/Content/ImagenFinal.css" rel="stylesheet" />
</head>
<body>

    @Html.Partial("_ProgressBar4")

    <h2>¡Listo!</h2>

    <div id="imagen">
        <img src="~/Resources/TarjetaAImprimir.JPG" />
        <div>@ViewBag.Cliente</div>
    </div>
    <form>
        <input type='button' onclick='window.print();' value='Imprimir' />
    </form>
    <div class="progress" style="margin:100px">
        <div id="bar" class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" style="width: 0%">
            <span class="sr-only">0% Complete</span>
        </div>
    </div>
    @section Scripts{
        <script src="~/Scripts/ProgressPrintTarjeta.js"></script>
    }
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Contrato/Index.cshtml
@model IEnumerable<Lppa.Data.Contrato>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaAlta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaBaja)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDCliente)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDTarjeta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IDUsuario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CodEstado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedOn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ChangedOn)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaAlta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaBaja)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDCliente)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDTarjeta)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IDUsuario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CodEstado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedOn)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangedBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ChangedOn)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
                @Html.ActionLink("Details", "Details", new { id=item.ID }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.ID })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>