BaseLPPA/Presentation/Lppa.UI.Web/ViewModels/ClienteViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Lppa.UI.Web.ViewModels
{
    public class ClienteViewModel
    {
        [Required]
        public int DNI { get; set; }
       
        [Required]
        [StringLength(50, ErrorMessage = "El Nombre no puede tener mas de 50 caracteres")]
        public string Nombre { get; set; }

        [Required]
        [StringLength(50, ErrorMessage = "El Apellido no puede tener mas de 50 caracteres")]
        public string Apellido { get; set; }

        [Required]
        public string Sexo { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Fecha de Nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        [Required]
        [Display(Name = "Estado Civil")]
        public string EstadoCivil { get; set; }

        [Required]
        public string Ocupacion { get; set; }

        [Required]
        public decimal Ingreso { get; set; }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/ClienteController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;
using Lppa.UI.Process;
using Lppa.Entities;

namespace Lppa.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        private LppaBD db = new LppaBD();
        public string resultado { get; set; }

        public ActionResult Index()
        {
            ViewBag.Veraz = resultado;
            return View(db.Cliente.ToList());
        }

        public ActionResult PasosCliente()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Contrato()
        {
            ViewBag.Progress = 3;
            return PartialView();
        }

        public ActionResult ValidarVeraz(long dni)
        {
            var vp = new VerazComponentController();
            resultado = vp.ValidarVeraz(dni);

            ViewBag.Veraz = resultado;
            ViewBag.DNI = dni;
            return RedirectToAction("Index", new { result = resultado });
        }

        [HttpPost]
        public ActionResult ValidarVeraz(string dni)
        {
            if (dni.ToString() == "Enviar consulta")
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
                var vp = new VerazComponentController();
                resultado = vp.ValidarVeraz(long.Parse(dni));

                ViewBag.Veraz = resultado;

                var customerFound = new ClienteRepository();
                var customer = customerFound.getID(long.Parse(dni));
                string NombreCliente = customer.Nombre + " " + customer.Apellido; 
             
                return RedirectToAction("DatosCliente", new { result = resultado, dni = dni, cliente = NombreCliente});
                //return RedirectToAction("DatosCliente");
            }


        }

        [HttpPost]
        public ActionResult Index(long dni)
        {


            var ccc = new ClienteComponentController();
            var nuevoCliente = ccc.BuscarPorDNI(dni);

            if (nuevoCliente == null)
            {

                return View(new List<Lppa.Data.Cliente>());

            }
            else
            {
                var c = new Cliente()
                {
                    Nombre = nuevoCliente.Nombre,
                    Apellido = nuevoCliente.Apellido,
                    DNI = nuevoCliente.DNI,
                    Domicilio = nuevoCliente.Domicilio,
                    Sexo = nuevoCliente.Sexo,
                    Ocupacion = nuevoCliente.Ocupacion,
                    FechaNacimiento = nuevoCliente.FechaNacimiento,
                    EstadoCivil = nuevoCliente.EstadoCivil,
                    Ingreso = nuevoCliente.Ingreso,
                    ChangedBy = nuevoCliente.ChangedBy,
                    ChangedOn = nuevoCliente.ChangedOn,
                    CodEstado = nuevoCliente.CodEstado,
                    CreatedBy = nuevoCliente.CreatedBy,
                    CreatedOn = nuevoCliente.CreatedOn
                };


                var lista = new List<Cliente>();
                lista.Add(c);

                return View(lista);
            }


        }

        // GET: Cliente/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewBag.Progress = 1;
            return View();


        }

        public ActionResult DatosCliente(string result, string dni, string cliente)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;
            ViewBag.Veraz = result;
            return View();
        }

  


        [HttpPost]
        public ActionResult DatosCliente(ClienteEntity cliente)
        {
            var ccc = new ClienteComponentController();
            ccc.AgregarunCliente(cliente);
            
            ViewBag.Cliente = cliente.Nombre + " " + cliente.Apellido;
            ViewBag.ClienteDNI = cliente.DNI;
          
            //return RedirectToAction("Index", new { result = "", dni = cliente.DNI });
            ViewBag.Respuesta = "Cliente " + ViewBag.Cliente + " fue creado con Exito!!";
            return View();


        }

        // POST: Cliente/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create([Bind(Include = "ID,Nombre,Apellido,DNI,Domicilio,EstadoCivil,FechaNacimiento,Ingreso,Sexo,Ocupacion,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Cliente cliente)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        db.Cliente.Add(cliente);
        //        db.SaveChanges();
        //        return RedirectToAction("Index");
        //    }

        //    return View(cliente);
        //}

        // GET: Cliente/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Nombre,Apellido,DNI,Domicilio,EstadoCivil,FechaNacimiento,Ingreso,Sexo,Ocupacion,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(cliente);
        }

        // GET: Cliente/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Cliente.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Cliente/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Cliente.Find(id);
            db.Cliente.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/ReporteController.cs
using Lppa.Data;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Lppa.UI.Web.Controllers
{
   
    public class ReporteController : Controller
    {
        private LppaBD db = new LppaBD();
    
        public ActionResult Principal()
        {
            return View();
        }

        public ActionResult ListaClientes()
        {
            return View(db.Cliente.ToList());
        }

        public ActionResult ListaClientesVISA()
        {
            try
            {
                var lista = (from a in db.Tarjeta join c in db.Cliente on a.IDCliente equals c.ID where a.Marca == "Visa" select new { c.Nombre, a.Marca, a.FechaEmision, a.FechaVencimiento, a.Limite }).ToList();
                var nuevaLista = new List<ViewModels.ClientesVisa>();

                foreach (var item in lista)
                {
                    var c = new ViewModels.ClientesVisa()
                    {
                        Nombre = item.Nombre,
                        MarcaTarjeta = item.Marca,
                        FechaEmision = item.FechaEmision,
                        FechaVencimiento = item.FechaVencimiento,
                        Limite = item.Limite
                    };

                    nuevaLista.Add(c);
                }

                return View(nuevaLista);
            }
            catch
            {
                return RedirectToAction("Principal");
            }
           
        }

        public ActionResult ListaClientesAMEX()
        {
            try
            {
                var lista = (from a in db.Tarjeta join c in db.Cliente on a.IDCliente equals c.ID where a.Marca == "American Express" select new { c.Nombre, a.Marca, a.FechaEmision, a.FechaVencimiento, a.Limite }).ToList();
                var nuevaLista = new List<ViewModels.ClientesAMEX>();

                foreach (var item in lista)
                {
                    var c = new ViewModels.ClientesAMEX()
                    {
                        Nombre = item.Nombre,
                        MarcaTarjeta = item.Marca,
                        FechaEmision = item.FechaEmision,
                        FechaVencimiento = item.FechaVencimiento,
                        Limite = item.Limite
                    };

                    nuevaLista.Add(c);
                }

                return View(nuevaLista);
            }
            catch
            {
                return RedirectToAction("Principal");
            }
        }

        public ActionResult ListaClientesMasterCard()
        {
            try
            {
                var lista = (from a in db.Tarjeta join c in db.Cliente on a.IDCliente equals c.ID where a.Marca == "MasterCard" select new { c.Nombre, a.Marca, a.FechaEmision, a.FechaVencimiento, a.Limite }).ToList();
                var nuevaLista = new List<ViewModels.ClientesMaster>();

                foreach (var item in lista)
                {
                    var c = new ViewModels.ClientesMaster()
                    {
                        Nombre = item.Nombre,
                        MarcaTarjeta = item.Marca,
                        FechaEmision = item.FechaEmision,
                        FechaVencimiento = item.FechaVencimiento,
                        Limite = item.Limite
                    };

                    nuevaLista.Add(c);
                }

                return View(nuevaLista);
            }
            catch
            {
                return RedirectToAction("Principal");
            }
        }

        public ActionResult ListaClientesEnVeraz()
        {
            var lista = new List<Veraz>();
            var listaFound = new VerazRepository();

            lista = listaFound.listaveraz();

            return View(lista);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Controllers/TarjetaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Lppa.Data;
using Lppa.Entities;
using Lppa.UI.Process;

namespace Lppa.UI.Web.Controllers
{
    public class TarjetaController : Controller
    {
        private LppaBD db = new LppaBD();

        // GET: Tarjeta
        public ActionResult Index()
        {
            return View(db.Tarjeta.ToList());
        }

        // GET: Tarjeta/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Create
        public ActionResult Create()
        {
            return View();
        }
        
        public ActionResult TarjetaCliente(string cliente, string dni)
        {
            ViewBag.Cliente = cliente;
            ViewBag.ClienteDNI = dni;
            return View();
        }

        [HttpPost]
        public ActionResult TarjetaCliente(TarjetaEntity tarjeta, string dni)
        {
            var tcc = new TarjetaComponentController();
            tcc.insert(tarjeta, long.Parse(dni));

            var customerFound = new ClienteRepository();
            var customer = customerFound.SearhByDNI(long.Parse(dni));
            string nombre = customer.Nombre + " " + customer.Apellido;
            ViewBag.Cliente = nombre;
            ViewBag.ClienteDNI = dni;
            return View();
        }

        //[HttpGet]
        //public ActionResult _TarjetaCliente(long dni)
        //{
        //    var ccc = new ClienteComponentController();
        //    ccc.BuscarPorDNI(dni);


        //    return View();
        //}



        // POST: Tarjeta/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,IDBanco,IDCliente,Marca,FechaEmision,FechaVencimiento,CodVerificacion,Limite,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Tarjeta tarjeta)
        {
            if (ModelState.IsValid)
            {
                db.Tarjeta.Add(tarjeta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tarjeta);
        }

        // GET: Tarjeta/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // POST: Tarjeta/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,IDBanco,IDCliente,Marca,FechaEmision,FechaVencimiento,CodVerificacion,Limite,CodEstado,CreatedBy,CreatedOn,ChangedBy,ChangedOn")] Tarjeta tarjeta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarjeta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tarjeta);
        }

        // GET: Tarjeta/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            if (tarjeta == null)
            {
                return HttpNotFound();
            }
            return View(tarjeta);
        }

        // POST: Tarjeta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Tarjeta tarjeta = db.Tarjeta.Find(id);
            db.Tarjeta.Remove(tarjeta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

BaseLPPA/Presentation/Lppa.UI.Web/Views/Cliente/Create.cshtml
@model Lppa.Data.Cliente

@using Lppa.Entities



@{
    ViewBag.Title = "Nuevo Cliente";
}


<html>
<head>

    <script type="text/javascript" src="js/jquery.min.js"></script>
    <link href="~/Content/ProgressBar.css" rel="stylesheet" />


</head>
<body>
    <h2 class="NuevoCliente">Nueva Solicitud de Tarjeta</h2>

    <!--ProgressBar-->
    @Html.Partial("_ProgressBar")


    @if (ViewBag.Progress == 1)
    {
         <!--Pantalla PRINCIPAL-->
        <div id="pantalla">

            @using (Html.BeginForm("Create", "Cliente", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.Partial("_DatosCliente")

                <div class="form-group">
                    <div class="col-md-offset-10 col-md-10">
                        <input type="submit" value="Siguiente" id="btnSiguiente" class="btn btn-primary" />

                    </div>
                </div>
            }
        </div>
    }
    else if (ViewBag.Progress == 2)
    {
         <!-- Comienzo PANTALLA 2 -->
        <div id="pantalla2">
            @using (Html.BeginForm("Create", "Cliente", FormMethod.Post))
            {
                @Html.AntiForgeryToken()
                @Html.Partial("_TarjetaCliente")
              
                <div class="form-group">
                    <div class="col-md-offset-10 col-md-10">
                        <input type="submit" value="Siguiente" id="btnSiguiente2" class="btn btn-primary" />

                    </div>
                </div>
            }

        </div>

    }

    else if (ViewBag.Progress == 3)
    {
         <!-- Comienzo PANTALLA 3 -->
        <div id="pantalla3">
            @Html.Partial("_ContratoCliente")
            <div class="form-group">
                <div class="col-md-offset-10 col-md-10">
                    <input type="submit" value="Ir a Paso1" id="btnaPaso2" class="btn btn-info" />
                    <input type="submit" value="Siguiente" id="btnSiguiente3" class="btn btn-primary" />
                </div>
            </div>


        </div>

    }
    else if (ViewBag.Progress == 4)
    {
        <!-- Comienzo PANTALLA 4 -->
        <div id="pantalla4" style="display:none;">
            <h2>PANTALLA 4</h2>
            <div class="form-group">
                <div class="col-md-offset-10 col-md-10">
                    <input type="submit" value="Ir a Paso1" id="btnaPaso3" class="btn btn-info" />
                    <input type="submit" value="Siguiente" id="btnFinalizar" class="btn btn-primary" />
                </div>
            </div>


        </div>

    }

    @section Scripts{
        <script src="~/Scripts/ProgressBar.js"></script>
    }

</body>

</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Cliente/DatosCliente.cshtml
@model Lppa.Data.Cliente
@{
    ViewBag.Title = "Nuevo Cliente";

}
<html>
<head>
    <script type="text/javascript" src="js/jquery.min.js"></script>
    <link href="~/Content/ProgressBar.css" rel="stylesheet" />
</head>
<body>

    @Html.Partial("_ProgressBar1")

    @using (Html.BeginForm("ValidarVeraz", "Cliente", FormMethod.Post, new { dni = ViewBag.ClienteDNI }))
    {
        <p>Validar DNI: </p>
        <input type="submit" value=@ViewBag.ClienteDNI name="DNI" />

    }
    <button onclick="myFunction()" style="float:right;">Resultado Veraz</button>

    

    @using (Html.BeginForm("DatosCliente", "Cliente", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div id="pantalla">


            <div class="form-horizontal">
                <h2>Ingresar Datos del Cliente</h2>
                <hr />
                <div class="col-md-6">
                    <div class="panel panel-success">
                        <div class="panel-heading panel-title" style="background-color:#00adff; color:antiquewhite;">Datos Personales</div>
                        <div class="panel-body">
                            <div class="form-group col-md-6">
                                @Html.LabelFor(m => m.Nombre)
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.TextBoxFor(m => m.Nombre, new { @class = "form-control required" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(m => m.Apellido)
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
                                    @Html.TextBoxFor(m => m.Apellido, new { @class = "form-control required" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(m => m.DNI)
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-chevron-right"></i></span>
                                    @Html.TextBoxFor(m => m.DNI, new { @class = "form-control required" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                @{
                                    var estadoCivil = new List<SelectListItem>()
                            {
                                new SelectListItem() {Text = "Soltero", Value = "Soltero"},
                                new SelectListItem() {Text = "Casado", Value = "Casado"},
                                new SelectListItem() {Text = "En Concubinato", Value = "En Concubinato"}
                            };
                                }
                                @Html.LabelFor(m => m.EstadoCivil)
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </span>
                                    @Html.DropDownListFor(m => m.EstadoCivil, estadoCivil, new { @class = "form-control" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                @{
                                    var sexo = new List<SelectListItem>()
                            {
                                new SelectListItem() {Text = "Masculino", Value = "Masculino"},
                                new SelectListItem() {Text = "Femenino", Value = "Femenino"}
                            };
                                }
                                @Html.LabelFor(m => m.Sexo)
                                <div class="input-group">
                                    <span class="input-group-addon">
                                        <span class="glyphicon glyphicon-chevron-right"></span>
                                    </span>
                                    @Html.DropDownListFor(m => m.Sexo, sexo, new { @class = "form-control required" })
                                </div>
                            </div>
                            <div class="form-group col-md-6">
                                @Html.LabelFor(m => m.FechaNacimiento)
                                <div class="input-group">
                                    <span class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></span>
                                    @Html.TextBoxFor(m => m.FechaNacimiento, new { @class = "form-control required" })
                                    @*@Html.TextBoxFor(m => m.FechaNacimiento, new { @Value = Model.FechaNacimiento.ToString("dd/MM/yyyy"), @class = "form-control datepicker required"})*@
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>

            <div class="col-md-6">
                <div class="panel panel-success">
                    <div class="panel-heading panel-title" style="background-color:#00adff; color:antiquewhite;">Información Adicional</div>
                    <div class="panel-body">
                        <div class="form-group col-md-6">
                            @{
                                var opcionesOcupacion = new List<SelectListItem>(){
                                new SelectListItem(){ Text = "Rel. Dependencia", Value = "Relación Dependencia" },
                                new SelectListItem(){ Text = "Monotributista", Value = "Monotributista" },
                                new SelectListItem(){ Text = "Independiente", Value = "Independiente" },
                                new SelectListItem(){ Text = "En Pasantía", Value = "En Pasantía" },

                            };
                            }
                            @Html.LabelFor(m => m.Ocupacion)
                            <div class="input-group">
                                <span class="input-group-addon">
                                    <span class="glyphicon glyphicon-briefcase"></span>
                                </span>
                                @Html.DropDownListFor(m => m.Ocupacion, opcionesOcupacion, new { @class = "form-control required" })
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Ingreso)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-usd"></i></span>
                                @Html.TextBoxFor(m => m.Ingreso, new { @class = "form-control required" })
                            </div>
                        </div>
                        <div class="form-group col-md-6">
                            @Html.LabelFor(m => m.Domicilio)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-home"></i></span>
                                @Html.TextBoxFor(m => m.Domicilio, new { @class = "form-control required" })
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>

        @*<div class="form-group">
            <div class="col-md-offset-11 col-md-10">*@
                <input type="submit" value="Guardar" id="btnSiguiente" class="btn btn-primary" />
            @*</div>
        </div>*@

       

                                }

    <div style="margin-left:95%";>
        @*<div class="col-md-offset-10 col-md-10">*@
            @Html.ActionLink("Continuar", "TarjetaCliente", "Tarjeta", new { cliente = ViewBag.Cliente, dni = ViewBag.ClienteDNI }, null)
        @*</div>*@
    </div>

    @section Scripts{
        <script>
            function myFunction() {
                alert("@ViewBag.Veraz");
            }
        </script>
    }
</body>
</html>

BaseLPPA/Presentation/Lppa.UI.Web/Views/Cliente/Index.cshtml
@model IEnumerable<Lppa.Data.Cliente>

@{
    ViewBag.Title = "Clientes";
   

}

<p>@ViewBag.Veraz</p>

<h2 class="ListaClientes">Lista de Clientes</h2>
<p>
    @Html.ActionLink("Atras", "Principal","Reporte")
</p>

@using (Html.BeginForm("Index", "Cliente", FormMethod.Post, new { @class = "form" }))
{   <div class="input-group">
        <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
        <input id="dniCliente" type="text" class="form-control" name="DNI" placeholder="DNI" style="width:200px;">

    </div>

}
<br />
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Apellido)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DNI)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Domicilio)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EstadoCivil)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.FechaNacimiento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ingreso)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Ocupacion)
        </th>

        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Apellido)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DNI)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Domicilio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstadoCivil)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimiento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ingreso)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Sexo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Ocupacion)
            </td>
            <td>
                @*@Html.ActionLink("Editar", "Edit", new { id = item.ID })*@

            </td>
        </tr>
    }



</table>

@*<button style="float:right;">
    @Html.ActionLink("Continuar Solicitud", "PasosCliente")
</button>*@

@*@section Scripts{
    <script>
        function myFunction() {
            alert("@ViewBag.Veraz");
        }
    </script>
}*@